[workspace]
resolver = "1"
members = [
  "protocol/rtmp",
  "protocol/hls",
  "library/bytesio",
  "library/container/flv",
  "library/container/mpegts",
  "library/codec/h264",
  "library/logger",
  "library/streamhub",
  "library/common",
  "chain-streamer",
]
