[package]
name = "env_logger_extend"
version = "0.1.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
env_logger = "0.10.0"
job_scheduler_ng = "2.0.4"
chrono = "0.4"
failure = "0.1.8"
log = "0.4.0"
