[package]
name = "commonlib"
version = "0.1.1"
edition = "2018"

[dependencies]
env_logger = "0.11.5"
job_scheduler_ng = "2.0.4"
chrono = "0.4"
failure = "0.1.8"
log = "0.4.0"
indexmap = "2.6.0"
md5 = "0.7.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
sui_sdk = { git = "https://github.com/MystenLabs/sui", package = "sui-sdk"}
sui-keys = { git = "https://github.com/MystenLabs/sui", package = "sui-keys"}
sui-config = { git = "https://github.com/MystenLabs/sui", package = "sui-config"}
shared-crypto = { git = "https://github.com/MystenLabs/sui", package = "shared-crypto"}
sui_json_rpc_types = { git = "https://github.com/MystenLabs/sui", package = "sui-json-rpc-types"}
sui-types = { git = "https://github.com/MystenLabs/sui", package = "sui-types"}
serde_json = "1.0.133"
tracing = "0.1.40"
anyhow = "1.0.93"
bcs = "0.1.6"
futures = "0.3.31"
tokio = "1.41.1"
reqwest = "0.12.9"
