[package]
name = "commonlib"
version = "0.1.1"
edition = "2018"

[dependencies]
anyhow = "^1.0"
env_logger = "0.11.5"
job_scheduler_ng = "2.0.4"
chrono = "0.4"
failure = "0.1.8"
log = "0.4.0"
indexmap = "2.6.0"
md5 = "0.7.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_derive = "1.0"
